# Introdução à Ciência de Dados - UFPB
Professor: Yuri Malheiros

## NumPy

Implemente a função `distance` abaixo. Ela deve receber dois pontos e retornar a distância euclidiana entre eles. Cada ponto é representado por um array do NumPy, por exemplo, `p1 = np.array([2,4])` representa o ponto com coordenadas `x=2` e `y=2`.

In [ ]:
import numpy as np

def distance(p1, p2):
  p3 = p1 - p2
  p3 = p3*p3
  p4 = np.sum(p3, axis=1)
  p4 = np.sqrt(p4)
  return p4

    """
    >>> distance(np.array([0,0]), np.array([1,1]))
    1.4142135623730951
    
    >>> distance(np.array([1,2]), np.array([3,4]))
    2.8284271247461903
    
    >>> distance(np.array([5,2]), np.array([-2,-1]))
    7.615773105863909
    """

    # ADICIONE O SEU CÓDIGO AQUI

Implemente a função `n_distances` abaixo. Ela recebe um ponto (`p1`), como um array do NumPy, e uma lista de pontos (`points`), uma matriz do NumPy, onde cada linha representa um ponto.

Esta função deve retornar a distância de `p1` para todos os pontos da matriz `points`. O retorno também é uma matriz, onde cada linha tem a distância de `p1` para o ponto daquela linha.

In [ ]:
def n_distances(p1, points):
  p3 = p1 - points
  p3 = p3*p3
  p4 = np.sum(p3, axis=1)
  p4 = np.sqrt(p4)
  return p4

    """
    >>> n_distances(np.array([0,0]), np.array([[1,1]]))
    array([1.41421356])
    
    >>> n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
    array([1.41421356, 2.82842712])
    
    >>> n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
    """
    
    # ADICIONE O SEU CÓDIGO AQUI

## Teste

In [ ]:
import doctest

doctest.testmod(verbose=True)